name: CI

on:
  # schedule:
   # - cron: "*/60 * * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    name: "Run"
    runs-on: "ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-md"
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: uptime
        run: uptime
      - name: installed
        run: "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed"
      - name: test
        run: "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \"platforms;android-35\" \"system-images;android-35;google_apis;x86_64\""
