name: GPU benchmarks

on:
  push:

jobs:
  macos:
    strategy:
      matrix:
        runs-on:
          - ghcr.io/cirruslabs/ubuntu-runner-amd64-gpu:22.04
          - group: github-gpu-runners

    name: "HuggingFace's Optimum-Benchmark"

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/setup-python@v5
      - run: git clone https://github.com/huggingface/optimum-benchmark.git
      - run: cd optimum-benchmark && sudo pip install -e .
      - run: cd optimum-benchmark && sudo optimum-benchmark --config-dir examples/ --config-name pytorch_bert
